apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgB24I4ozcD7lKRiBW1lWzBMCt5Vk+cgQ2pcyxnkh5Gq6WTQMxLC5JL+p7MNf7RZIejwGCZ+jta+fQIfxhkFC3nLdERWGvE5B3vdbd+0vcZkXHqs3MtYBz2nR7BDJjIfm5Yt3cGBN3YEkj7Rt8i91avObasX9h9fssuEd93kXVeRGX6W3waKJENRJE6yQBzoswDmBICGowY5f/YISLoYJZaac/4VtiiMWLYaZX4M73qfXanyQZBJ9ly8hIsSgKDCKcZbpvMSx2PQDwqh/A73iuibN7XJNontSRxmIYNTq4rpL5hMaEVdQyQoGIt5QHkbvoXs0ZdJg4jrgW8FMLPua9un1jp5hy3SE582jNKAYfJVxsMnpqFikRPrCcwf2es9bS7VALwzm/bEdGFrVCoh+D0HEk6Aoy0cESI9ixFri+uTSR2j0lvhik/2CGDz4B/M8IKT2qAbc+FQhSaHIIreYDlRg4G6WqxocnfzaNtXkHPGOoPzGA1gBU6sYHY6GMqNGEIjvOoYe4+p3IXIWUgr7UbMbgEtd9YNJQFO1WFxyHyxmUaF07VogtkUyutPCvkGSp93Yz8ZzV6MOabioEmd5vFCtwvzUI5Gy0f5r2TSvm8Nl6JNBQxjYHulO8zh1cq1h+FCHYqniZNcYlGd8j4/SK2w8Tso4060a9gBRJ7FMq5hAntEvAEeXOmNwwd25+jEK0owUXLxkAaoFQnhBBRWnPyUQ78ZSSl0remytbhKGfh34X46XD/xky5syy87tCc3at4dpD4AL1ZXZkXuSNspRbx+Qr2lbzpX3uRgfqg2R4nWzkGT6MzBtCj1H7xXRdXWv3576J9ovulm06RiyEsU6bcTpQuutIYbGX2gYQw63trKbi7sFyj3Zpu4c6RQHKSIeivu7Rhx2Rb9Yq/ISQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

