apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: argo-cd/overlays/production
    repoURL: https://github.com/ariansvi/argo-combined-demo
    targetRevision: HEAD
  destination:
    automated:
      selfHeal: true
      prune: true
